### ISSUE TITLE
Configmap "trino-cfg-vol" not found

### ISSUE THREAD

**Issue by ramondeklein** [joshuarobinson/presto-on-k8s#2]
I am following your blog and this repo to install Trino in my EKS cluster. The `trino.yaml` references the **trino-configs** configmap, but I cannot find it anywhere in your repo. When I checkout an older version of this repo, I see there is a custom dockerfile that has the proper configmap. Am I missing something or has it accidentally been deleted from this repo?

**Comment by joshuarobinson** [comment]
thanks for catching!  I missed the upload when I converted from Presto to Trino, it should there now
